spring:
  application:
    name: wooamo_test
  config:
    import: optional:file:env[.properties]

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/sample
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
