name: Github Action 실행시켜보기 # Workflow (하나의 단위)

on: # Event (실행 시점 설정 : 어느 시점에 github actions 의 로직을 실행할건지)
  push: # main 브랜치에 push 된 경우
    branches:
      - main

jobs: # 하나의 workflow 는 1개 이상의 job 으로 구성

  My-Deploy-Job: # job 을 식별하기 위한 id
    runs-on: ubuntu-latest # ubuntu 환경

    steps: # 특정 작업을 수행하는 가장 작은 단위 (job 은 여러 step 으로 구성)
      - name: Hello World 찍기
        run: echo "Hello World" # 실제 코드 작성
      - name: 여러 명령어 문장 작성하기
        run: | 
          echo "Good"
          echo "Morning"